apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-custom
  title: "GitHub Custom Action"
  description: "Trigger a custom GitHub action."
spec:
  owner: user:guest
  type: service
  parameters:
    - title: GitHub Workflow Configuration
      required:
        - repoOwner
        - repoName
        - workflowId
        - githubToken
        - ref
      properties:
        repoOwner:
          title: "Repository Owner"
          type: string
          description: "The owner of the GitHub repository."
        repoName:
          title: "Repository Name"
          type: string
          description: "The name of the GitHub repository."
        workflowId:
          title: "Workflow ID or Filename"
          type: string
          description: "The ID or filename of the GitHub Actions workflow."
        githubToken:
          title: "GitHub Token"
          type: string
          description: "A GitHub token with permissions to trigger workflows."
          ui:widget: "password"
        ref:
          title: "Branch or Tag"
          type: string
          description: "The name of the branch or tag to trigger the workflow on."
  steps:
    - id: custom-github-action
      name: "Trigger GitHub Action"
      action: custom:github
      input:
        repoOwner: ${{ parameters.repoOwner }}
        repoName: ${{ parameters.repoName }}
        workflowId: ${{ parameters.workflowId }}
        githubToken: ${{ parameters.githubToken }}
        ref: ${{ parameters.ref }}
