apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-custom
  title: github custom
  description: custom github
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Application and Repository Configuration
      required:
        - name
        - repoUrl
      properties:
        name:
          title: App Name
          type: string
          description: "Unique name for your app"
          ui:autofocus: true
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: custom-github-action
      name: Custom GitHub Action
      action: custom:github
      input:
        # Input parameters for your custom action
        someParameter: "Some value"
        anotherParameter: ${{ parameters.name }}
/ 
